#!/usr/bin/env bash

UNAMEOUT="$(uname -s)"

WHITE='\033[1;37m'
NC='\033[0m'

# Verify operating system is supported...
case "${UNAMEOUT}" in
    Linux*)             MACHINE=linux;;
    Darwin*)            MACHINE=mac;;
    *)                  MACHINE="UNKNOWN"
esac

if [ "$MACHINE" == "UNKNOWN" ]; then
    echo "Unsupported operating system [$(uname -s)]. Docky supports macOS, Linux, and Windows (WSL2)." >&2

    exit 1
fi

# Define environment variables...
export CONTAINER_APP_NAME=${CONTAINER_APP_NAME:-"app"}
export DB_PORT=${DB_PORT:-3306}
export CONTAINER_USER_NAME=${CONTAINER_USER_NAME}

if [ "$MACHINE" == "linux" ]; then
    export SEDCMD="sed -i"
elif [ "$MACHINE" == "mac" ]; then
    export SEDCMD="sed -i .bak"
fi

# Ensure that Docker is running...
if ! docker info > /dev/null 2>&1; then
    echo -e "${WHITE}Docker is not running.${NC}" >&2

    exit 1
fi

# Determine if Docky is currently up...
PSRESULT="$(docker-compose ps -q)"

if docker-compose ps | grep 'Exit'; then
    echo -e "${WHITE}Shutting down old Docky processes...${NC}" >&2

    docker-compose down > /dev/null 2>&1

    EXEC="no"
elif [ -n "$PSRESULT" ]; then
    EXEC="yes"
else
    EXEC="no"
fi

# Function that outputs Docky is not running...
function docky_is_not_running {
    echo -e "${WHITE}Docky are not running.${NC}" >&2
    echo "" >&2
    echo -e "${WHITE}You may Docky using the following commands:${NC} './docky up' or './docky up -d'" >&2

    exit 1
}

if [ $# -gt 0 ]; then
    # Source the ".env" file so environment variables are available...
    if [ -f ./.env ]; then
        source ./.env
    fi

    # Proxy PHP commands to the "php" binary on the application container...
    if [ "$1" == "php" ]; then
        shift 1

        if [ "$EXEC" == "yes" ]; then
            docker-compose exec \
                -u $CONTAINER_USER_NAME  \
                "$CONTAINER_APP_NAME" \
                php "$@"
        else
            docky_is_not_running
        fi

    # Initiate a Bash shell within the application container...
    elif [ "$1" == "shell" ] || [ "$1" == "bash" ] || [ "$1" == "sh" ]; then
        shift 1

        if [ "$EXEC" == "yes" ]; then
            docker-compose exec \
                -u $CONTAINER_USER_NAME  \
                "$CONTAINER_APP_NAME" \
                sh
        else
            docky_is_not_running
        fi

    # Initiate a root user Bash shell within the application container...
    elif [ "$1" == "root-shell" ] ; then
        shift 1

        if [ "$EXEC" == "yes" ]; then
            docker-compose exec \
                "$CONTAINER_APP_NAME" \
                bash
        else
            docky_is_not_running
        fi

    # Wordpress cli
    elif [ "$1" == "wp" ] ; then
          shift 1

          if [ "$EXEC" == "yes" ]; then
              docker-compose exec \
                  -u $CONTAINER_USER_NAME \
                  "$CONTAINER_APP_NAME" \
                  wp "$@"
          else
              docky_is_not_running
          fi
    # Pass unknown commands to the "docker-compose" binary...
    else
        docker-compose "$@"
    fi
else
    docker-compose ps
fi
